name: advent-of-code
version: 0.1.0.0
github: "stanosphere/advent-of-code"
license: BSD3
author: "Paul Stanford"
maintainer: "example@example.com"
copyright: "2023 Paul Stanford"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/stanosphere/advent-of-code#readme>

dependencies:
  - base >= 4.7 && < 5
  - split
  - containers
  - extra
  - parsec
  - transformers
  - array
  - mtl

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wno-missing-export-lists
  - -Wno-prepositive-qualified-module

library:
  source-dirs: src
